### ISSUE TITLE
Update to 1.21.1 pretty please

### ISSUE THREAD

**Issue by MrEizy** [CyclopsMC/EverlastingAbilities-PotionCore#10]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

**Comment by rubensworks** [comment]
PotionCore is not updated yet unfortunately: https://www.curseforge.com/minecraft/mc-mods/potion-core

<blockquote><img src="https://media.forgecdn.net/avatars/thumbnails/36/208/256/256/635935613362396350.png" width="48" align="right"><div>CurseForge</div><div><strong><a href="/minecraft/mc-mods/potion-core">Potion Core</a></strong></div><div>Adds a whole lot of potion effects to the game.
28.1M Downloads | Mods</div></blockquote>
