### ISSUE TITLE
"Bless" ability viability as a totem

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/EverlastingAbilities-PotionCore#2]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

When activating the "Bless" totem it will give you the random potion effect each tick which gets very chaotic, an extra setting in the configs for the mod to set the time in ticks between every single random potion given would be nice, making the bless totem actually usable.

**Comment by rubensworks** [comment]
Right, I though about doing this, but I forgot about this. I'll try to do this soon, thanks for the issue!
