### ISSUE TITLE
Small description problem with Magic Inhibition.

### ISSUE THREAD

**Issue by SirAron111** [CyclopsMC/EverlastingAbilities-PotionCore#4]
Magic Inhibition doesn’t make enemy weaker to magic it makes enemys magic attacks weaker so if a witch hits you with a dmg potion it does less damage the one that lets the player do more dmg to enemies is magic focus.

I noticed this when players of my pack reported to me that the totem doesn’t do what it promises to do. So I checked and checked on potion core and config. Found out the totem does what it should only the description doesn’t describe what inhibition does.

----
Solution: Change description of Magic Inhibition to Enemies in the area have their Magic Damage Reduced

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
