### ISSUE TITLE
Split up the Strange True shot dmg scaling that affects not only bow and arrow like projectiles But also other modded ones.

### ISSUE THREAD

**Issue by SirAron111** [CyclopsMC/EverlastingAbilities-PotionCore#6]
#### Issue type:

- :heavy_plus_sign: Split up the Strange True shot dmg scaling that affects not only bow and arrow like projectiles But also other modded ones.

____

#### Short description:

The Archery Totem effect doesn’t seem to scale up only ranged attacks from bows and the like, but also all other projectiles from mods. (Especially ebwiz spell dmg or botania stuff). Maybe split it in two parts. Or at least move the dmg increase for these magic mods to the magic dmg totem. Which currently only affects potions (sadly the totem doesn’t even say it only ups potion magic dmg so many players think it would upgrade the modded magic stuff)

**Comment by rubensworks** [comment]
This is unfortunately not something I can change, this would have to be done in the Potion Core mod, so I would suggest reporting this there.
